package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * AfiliadoId generated by hbm2java
 */
public class AfiliadoId implements java.io.Serializable {

	private String documento;
	private String nacionalidad;

	public AfiliadoId() {
	}

	public AfiliadoId(String documento, String nacionalidad) {
		this.documento = documento;
		this.nacionalidad = nacionalidad;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AfiliadoId))
			return false;
		AfiliadoId castOther = (AfiliadoId) other;

		return ((this.getDocumento() == castOther.getDocumento()) || (this
				.getDocumento() != null && castOther.getDocumento() != null && this
				.getDocumento().equals(castOther.getDocumento())))
				&& ((this.getNacionalidad() == castOther.getNacionalidad()) || (this
						.getNacionalidad() != null
						&& castOther.getNacionalidad() != null && this
						.getNacionalidad().equals(castOther.getNacionalidad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		result = 37
				* result
				+ (getNacionalidad() == null ? 0 : this.getNacionalidad()
						.hashCode());
		return result;
	}

}
