package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Afiliado generated by hbm2java
 */
public class Afiliado implements java.io.Serializable {

	private AfiliadoId id;
	private Tipodocumento tipodocumento;
	private Empresa empresa;
	private Usuario usuario;
	private String nombres;
	private String apellidos;
	private String sexo;
	private String telefonofijo;
	private String celular;
	private String departamento;
	private String ciudad;
	private Date fechanacimiento;
	private String street;
	private String streetvalor;
	private String streetdos;
	private String streetdosvalor;
	private String email;
	private Boolean emailvalidado;
	private Date fechavalidacionemail;
	private String urlimageperfil;
	private String facebookperfil;
	private String twitterperfil;
	private Date momento;
	private Integer idvendedor;
	private String usuarioweb;
	private String claveweb;
	private Set emailenvios = new HashSet(0);
	private Set puntoses = new HashSet(0);
	private Set smsbroadcasts = new HashSet(0);
	private Set emailbroadcasts = new HashSet(0);
	private Set smsenvios = new HashSet(0);

	public Afiliado() {
	}

	public Afiliado(AfiliadoId id, Tipodocumento tipodocumento,
			Empresa empresa, Usuario usuario, String nombres, String sexo,
			String telefonofijo, String celular, String departamento,
			String ciudad, String email, Date momento) {
		this.id = id;
		this.tipodocumento = tipodocumento;
		this.empresa = empresa;
		this.usuario = usuario;
		this.nombres = nombres;
		this.sexo = sexo;
		this.telefonofijo = telefonofijo;
		this.celular = celular;
		this.departamento = departamento;
		this.ciudad = ciudad;
		this.email = email;
		this.momento = momento;
	}

	public Afiliado(AfiliadoId id, Tipodocumento tipodocumento,
			Empresa empresa, Usuario usuario, String nombres, String apellidos,
			String sexo, String telefonofijo, String celular,
			String departamento, String ciudad, Date fechanacimiento,
			String street, String streetvalor, String streetdos,
			String streetdosvalor, String email, Boolean emailvalidado,
			Date fechavalidacionemail, String urlimageperfil,
			String facebookperfil, String twitterperfil, Date momento,
			Integer idvendedor, String usuarioweb, String claveweb,
			Set emailenvios, Set puntoses, Set smsbroadcasts,
			Set emailbroadcasts, Set smsenvios) {
		this.id = id;
		this.tipodocumento = tipodocumento;
		this.empresa = empresa;
		this.usuario = usuario;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.sexo = sexo;
		this.telefonofijo = telefonofijo;
		this.celular = celular;
		this.departamento = departamento;
		this.ciudad = ciudad;
		this.fechanacimiento = fechanacimiento;
		this.street = street;
		this.streetvalor = streetvalor;
		this.streetdos = streetdos;
		this.streetdosvalor = streetdosvalor;
		this.email = email;
		this.emailvalidado = emailvalidado;
		this.fechavalidacionemail = fechavalidacionemail;
		this.urlimageperfil = urlimageperfil;
		this.facebookperfil = facebookperfil;
		this.twitterperfil = twitterperfil;
		this.momento = momento;
		this.idvendedor = idvendedor;
		this.usuarioweb = usuarioweb;
		this.claveweb = claveweb;
		this.emailenvios = emailenvios;
		this.puntoses = puntoses;
		this.smsbroadcasts = smsbroadcasts;
		this.emailbroadcasts = emailbroadcasts;
		this.smsenvios = smsenvios;
	}

	public AfiliadoId getId() {
		return this.id;
	}

	public void setId(AfiliadoId id) {
		this.id = id;
	}

	public Tipodocumento getTipodocumento() {
		return this.tipodocumento;
	}

	public void setTipodocumento(Tipodocumento tipodocumento) {
		this.tipodocumento = tipodocumento;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getTelefonofijo() {
		return this.telefonofijo;
	}

	public void setTelefonofijo(String telefonofijo) {
		this.telefonofijo = telefonofijo;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getStreetvalor() {
		return this.streetvalor;
	}

	public void setStreetvalor(String streetvalor) {
		this.streetvalor = streetvalor;
	}

	public String getStreetdos() {
		return this.streetdos;
	}

	public void setStreetdos(String streetdos) {
		this.streetdos = streetdos;
	}

	public String getStreetdosvalor() {
		return this.streetdosvalor;
	}

	public void setStreetdosvalor(String streetdosvalor) {
		this.streetdosvalor = streetdosvalor;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Boolean getEmailvalidado() {
		return this.emailvalidado;
	}

	public void setEmailvalidado(Boolean emailvalidado) {
		this.emailvalidado = emailvalidado;
	}

	public Date getFechavalidacionemail() {
		return this.fechavalidacionemail;
	}

	public void setFechavalidacionemail(Date fechavalidacionemail) {
		this.fechavalidacionemail = fechavalidacionemail;
	}

	public String getUrlimageperfil() {
		return this.urlimageperfil;
	}

	public void setUrlimageperfil(String urlimageperfil) {
		this.urlimageperfil = urlimageperfil;
	}

	public String getFacebookperfil() {
		return this.facebookperfil;
	}

	public void setFacebookperfil(String facebookperfil) {
		this.facebookperfil = facebookperfil;
	}

	public String getTwitterperfil() {
		return this.twitterperfil;
	}

	public void setTwitterperfil(String twitterperfil) {
		this.twitterperfil = twitterperfil;
	}

	public Date getMomento() {
		return this.momento;
	}

	public void setMomento(Date momento) {
		this.momento = momento;
	}

	public Integer getIdvendedor() {
		return this.idvendedor;
	}

	public void setIdvendedor(Integer idvendedor) {
		this.idvendedor = idvendedor;
	}

	public String getUsuarioweb() {
		return this.usuarioweb;
	}

	public void setUsuarioweb(String usuarioweb) {
		this.usuarioweb = usuarioweb;
	}

	public String getClaveweb() {
		return this.claveweb;
	}

	public void setClaveweb(String claveweb) {
		this.claveweb = claveweb;
	}

	public Set getEmailenvios() {
		return this.emailenvios;
	}

	public void setEmailenvios(Set emailenvios) {
		this.emailenvios = emailenvios;
	}

	public Set getPuntoses() {
		return this.puntoses;
	}

	public void setPuntoses(Set puntoses) {
		this.puntoses = puntoses;
	}

	public Set getSmsbroadcasts() {
		return this.smsbroadcasts;
	}

	public void setSmsbroadcasts(Set smsbroadcasts) {
		this.smsbroadcasts = smsbroadcasts;
	}

	public Set getEmailbroadcasts() {
		return this.emailbroadcasts;
	}

	public void setEmailbroadcasts(Set emailbroadcasts) {
		this.emailbroadcasts = emailbroadcasts;
	}

	public Set getSmsenvios() {
		return this.smsenvios;
	}

	public void setSmsenvios(Set smsenvios) {
		this.smsenvios = smsenvios;
	}

}
