package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Audiwebservice generated by hbm2java
 */
public class Audiwebservice implements java.io.Serializable {

	private int idaudiwebservice;
	private Sucursal sucursal;
	private Eventowebservice eventowebservice;
	private String apikey;
	private String contenido;
	private Date fecharequest;

	public Audiwebservice() {
	}

	public Audiwebservice(int idaudiwebservice, Sucursal sucursal,
			Eventowebservice eventowebservice) {
		this.idaudiwebservice = idaudiwebservice;
		this.sucursal = sucursal;
		this.eventowebservice = eventowebservice;
	}

	public Audiwebservice(int idaudiwebservice, Sucursal sucursal,
			Eventowebservice eventowebservice, String apikey, String contenido,
			Date fecharequest) {
		this.idaudiwebservice = idaudiwebservice;
		this.sucursal = sucursal;
		this.eventowebservice = eventowebservice;
		this.apikey = apikey;
		this.contenido = contenido;
		this.fecharequest = fecharequest;
	}

	public int getIdaudiwebservice() {
		return this.idaudiwebservice;
	}

	public void setIdaudiwebservice(int idaudiwebservice) {
		this.idaudiwebservice = idaudiwebservice;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public Eventowebservice getEventowebservice() {
		return this.eventowebservice;
	}

	public void setEventowebservice(Eventowebservice eventowebservice) {
		this.eventowebservice = eventowebservice;
	}

	public String getApikey() {
		return this.apikey;
	}

	public void setApikey(String apikey) {
		this.apikey = apikey;
	}

	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	public Date getFecharequest() {
		return this.fecharequest;
	}

	public void setFecharequest(Date fecharequest) {
		this.fecharequest = fecharequest;
	}

}
