package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * Condicionservicio generated by hbm2java
 */
public class Condicionservicio implements java.io.Serializable {

	private CondicionservicioId id;
	private Contrato contrato;
	private int basegravable;
	private int factorpuntos;
	private boolean enviosms;
	private boolean envioemail;

	public Condicionservicio() {
	}

	public Condicionservicio(CondicionservicioId id, Contrato contrato,
			int basegravable, int factorpuntos, boolean enviosms,
			boolean envioemail) {
		this.id = id;
		this.contrato = contrato;
		this.basegravable = basegravable;
		this.factorpuntos = factorpuntos;
		this.enviosms = enviosms;
		this.envioemail = envioemail;
	}

	public CondicionservicioId getId() {
		return this.id;
	}

	public void setId(CondicionservicioId id) {
		this.id = id;
	}

	public Contrato getContrato() {
		return this.contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

	public int getBasegravable() {
		return this.basegravable;
	}

	public void setBasegravable(int basegravable) {
		this.basegravable = basegravable;
	}

	public int getFactorpuntos() {
		return this.factorpuntos;
	}

	public void setFactorpuntos(int factorpuntos) {
		this.factorpuntos = factorpuntos;
	}

	public boolean isEnviosms() {
		return this.enviosms;
	}

	public void setEnviosms(boolean enviosms) {
		this.enviosms = enviosms;
	}

	public boolean isEnvioemail() {
		return this.envioemail;
	}

	public void setEnvioemail(boolean envioemail) {
		this.envioemail = envioemail;
	}

}
