package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * CondicionservicioId generated by hbm2java
 */
public class CondicionservicioId implements java.io.Serializable {

	private int idcontrato;
	private int idempresa;
	private boolean redensionsucursales;

	public CondicionservicioId() {
	}

	public CondicionservicioId(int idcontrato, int idempresa,
			boolean redensionsucursales) {
		this.idcontrato = idcontrato;
		this.idempresa = idempresa;
		this.redensionsucursales = redensionsucursales;
	}

	public int getIdcontrato() {
		return this.idcontrato;
	}

	public void setIdcontrato(int idcontrato) {
		this.idcontrato = idcontrato;
	}

	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	public boolean isRedensionsucursales() {
		return this.redensionsucursales;
	}

	public void setRedensionsucursales(boolean redensionsucursales) {
		this.redensionsucursales = redensionsucursales;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CondicionservicioId))
			return false;
		CondicionservicioId castOther = (CondicionservicioId) other;

		return (this.getIdcontrato() == castOther.getIdcontrato())
				&& (this.getIdempresa() == castOther.getIdempresa())
				&& (this.isRedensionsucursales() == castOther
						.isRedensionsucursales());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcontrato();
		result = 37 * result + this.getIdempresa();
		result = 37 * result + (this.isRedensionsucursales() ? 1 : 0);
		return result;
	}

}
