package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato implements java.io.Serializable {

	private ContratoId id;
	private Empresa empresa;
	private Date fechainicio;
	private Date fechafin;
	private Set instancias = new HashSet(0);
	private Set condicionservicios = new HashSet(0);

	public Contrato() {
	}

	public Contrato(ContratoId id, Empresa empresa, Date fechainicio,
			Date fechafin) {
		this.id = id;
		this.empresa = empresa;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
	}

	public Contrato(ContratoId id, Empresa empresa, Date fechainicio,
			Date fechafin, Set instancias, Set condicionservicios) {
		this.id = id;
		this.empresa = empresa;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.instancias = instancias;
		this.condicionservicios = condicionservicios;
	}

	public ContratoId getId() {
		return this.id;
	}

	public void setId(ContratoId id) {
		this.id = id;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public Set getInstancias() {
		return this.instancias;
	}

	public void setInstancias(Set instancias) {
		this.instancias = instancias;
	}

	public Set getCondicionservicios() {
		return this.condicionservicios;
	}

	public void setCondicionservicios(Set condicionservicios) {
		this.condicionservicios = condicionservicios;
	}

}
