package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * DetransaccionId generated by hbm2java
 */
public class DetransaccionId implements java.io.Serializable {

	private int iddetransaccion;
	private int idtransaccion;

	public DetransaccionId() {
	}

	public DetransaccionId(int iddetransaccion, int idtransaccion) {
		this.iddetransaccion = iddetransaccion;
		this.idtransaccion = idtransaccion;
	}

	public int getIddetransaccion() {
		return this.iddetransaccion;
	}

	public void setIddetransaccion(int iddetransaccion) {
		this.iddetransaccion = iddetransaccion;
	}

	public int getIdtransaccion() {
		return this.idtransaccion;
	}

	public void setIdtransaccion(int idtransaccion) {
		this.idtransaccion = idtransaccion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetransaccionId))
			return false;
		DetransaccionId castOther = (DetransaccionId) other;

		return (this.getIddetransaccion() == castOther.getIddetransaccion())
				&& (this.getIdtransaccion() == castOther.getIdtransaccion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIddetransaccion();
		result = 37 * result + this.getIdtransaccion();
		return result;
	}

}
