package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * Detransaccion generated by hbm2java
 */
public class Detransaccion implements java.io.Serializable {

	private DetransaccionId id;
	private Transaccion transaccion;
	private Producto producto;
	private int cantidad;

	public Detransaccion() {
	}

	public Detransaccion(DetransaccionId id, Transaccion transaccion,
			Producto producto, int cantidad) {
		this.id = id;
		this.transaccion = transaccion;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	public DetransaccionId getId() {
		return this.id;
	}

	public void setId(DetransaccionId id) {
		this.id = id;
	}

	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
