package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Emailestado generated by hbm2java
 */
public class Emailestado implements java.io.Serializable {

	private EmailestadoId id;
	private Tipoestaestadoemail tipoestaestadoemail;
	private Emailenvio emailenvio;
	private Date fechaestado;

	public Emailestado() {
	}

	public Emailestado(EmailestadoId id,
			Tipoestaestadoemail tipoestaestadoemail, Emailenvio emailenvio) {
		this.id = id;
		this.tipoestaestadoemail = tipoestaestadoemail;
		this.emailenvio = emailenvio;
	}

	public Emailestado(EmailestadoId id,
			Tipoestaestadoemail tipoestaestadoemail, Emailenvio emailenvio,
			Date fechaestado) {
		this.id = id;
		this.tipoestaestadoemail = tipoestaestadoemail;
		this.emailenvio = emailenvio;
		this.fechaestado = fechaestado;
	}

	public EmailestadoId getId() {
		return this.id;
	}

	public void setId(EmailestadoId id) {
		this.id = id;
	}

	public Tipoestaestadoemail getTipoestaestadoemail() {
		return this.tipoestaestadoemail;
	}

	public void setTipoestaestadoemail(Tipoestaestadoemail tipoestaestadoemail) {
		this.tipoestaestadoemail = tipoestaestadoemail;
	}

	public Emailenvio getEmailenvio() {
		return this.emailenvio;
	}

	public void setEmailenvio(Emailenvio emailenvio) {
		this.emailenvio = emailenvio;
	}

	public Date getFechaestado() {
		return this.fechaestado;
	}

	public void setFechaestado(Date fechaestado) {
		this.fechaestado = fechaestado;
	}

}
