package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EmailbroadcastId generated by hbm2java
 */
public class EmailbroadcastId implements java.io.Serializable {

	private String idafiliado;
	private Date instanteenvio;
	private String nacionalidad;

	public EmailbroadcastId() {
	}

	public EmailbroadcastId(String idafiliado, Date instanteenvio,
			String nacionalidad) {
		this.idafiliado = idafiliado;
		this.instanteenvio = instanteenvio;
		this.nacionalidad = nacionalidad;
	}

	public String getIdafiliado() {
		return this.idafiliado;
	}

	public void setIdafiliado(String idafiliado) {
		this.idafiliado = idafiliado;
	}

	public Date getInstanteenvio() {
		return this.instanteenvio;
	}

	public void setInstanteenvio(Date instanteenvio) {
		this.instanteenvio = instanteenvio;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmailbroadcastId))
			return false;
		EmailbroadcastId castOther = (EmailbroadcastId) other;

		return ((this.getIdafiliado() == castOther.getIdafiliado()) || (this
				.getIdafiliado() != null && castOther.getIdafiliado() != null && this
				.getIdafiliado().equals(castOther.getIdafiliado())))
				&& ((this.getInstanteenvio() == castOther.getInstanteenvio()) || (this
						.getInstanteenvio() != null
						&& castOther.getInstanteenvio() != null && this
						.getInstanteenvio()
						.equals(castOther.getInstanteenvio())))
				&& ((this.getNacionalidad() == castOther.getNacionalidad()) || (this
						.getNacionalidad() != null
						&& castOther.getNacionalidad() != null && this
						.getNacionalidad().equals(castOther.getNacionalidad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdafiliado() == null ? 0 : this.getIdafiliado()
						.hashCode());
		result = 37
				* result
				+ (getInstanteenvio() == null ? 0 : this.getInstanteenvio()
						.hashCode());
		result = 37
				* result
				+ (getNacionalidad() == null ? 0 : this.getNacionalidad()
						.hashCode());
		return result;
	}

}
