package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Emailenvio generated by hbm2java
 */
public class Emailenvio implements java.io.Serializable {

	private EmailenvioId id;
	private Afiliado afiliado;
	private Tipoemail tipoemail;
	private Transaccion transaccion;
	private Date fechaenvio;
	private int estadoemail;
	private Date fechaestado;
	private Set emailestados = new HashSet(0);

	public Emailenvio() {
	}

	public Emailenvio(EmailenvioId id, Afiliado afiliado, Tipoemail tipoemail,
			Date fechaenvio, int estadoemail, Date fechaestado) {
		this.id = id;
		this.afiliado = afiliado;
		this.tipoemail = tipoemail;
		this.fechaenvio = fechaenvio;
		this.estadoemail = estadoemail;
		this.fechaestado = fechaestado;
	}

	public Emailenvio(EmailenvioId id, Afiliado afiliado, Tipoemail tipoemail,
			Transaccion transaccion, Date fechaenvio, int estadoemail,
			Date fechaestado, Set emailestados) {
		this.id = id;
		this.afiliado = afiliado;
		this.tipoemail = tipoemail;
		this.transaccion = transaccion;
		this.fechaenvio = fechaenvio;
		this.estadoemail = estadoemail;
		this.fechaestado = fechaestado;
		this.emailestados = emailestados;
	}

	public EmailenvioId getId() {
		return this.id;
	}

	public void setId(EmailenvioId id) {
		this.id = id;
	}

	public Afiliado getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(Afiliado afiliado) {
		this.afiliado = afiliado;
	}

	public Tipoemail getTipoemail() {
		return this.tipoemail;
	}

	public void setTipoemail(Tipoemail tipoemail) {
		this.tipoemail = tipoemail;
	}

	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	public Date getFechaenvio() {
		return this.fechaenvio;
	}

	public void setFechaenvio(Date fechaenvio) {
		this.fechaenvio = fechaenvio;
	}

	public int getEstadoemail() {
		return this.estadoemail;
	}

	public void setEstadoemail(int estadoemail) {
		this.estadoemail = estadoemail;
	}

	public Date getFechaestado() {
		return this.fechaestado;
	}

	public void setFechaestado(Date fechaestado) {
		this.fechaestado = fechaestado;
	}

	public Set getEmailestados() {
		return this.emailestados;
	}

	public void setEmailestados(Set emailestados) {
		this.emailestados = emailestados;
	}

}
