package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Emailparametro generated by hbm2java
 */
public class Emailparametro implements java.io.Serializable {

	private Integer idemailparametro;
	private String nombreparametro;
	private Set empresaparametroemails = new HashSet(0);

	public Emailparametro() {
	}

	public Emailparametro(String nombreparametro, Set empresaparametroemails) {
		this.nombreparametro = nombreparametro;
		this.empresaparametroemails = empresaparametroemails;
	}

	public Integer getIdemailparametro() {
		return this.idemailparametro;
	}

	public void setIdemailparametro(Integer idemailparametro) {
		this.idemailparametro = idemailparametro;
	}

	public String getNombreparametro() {
		return this.nombreparametro;
	}

	public void setNombreparametro(String nombreparametro) {
		this.nombreparametro = nombreparametro;
	}

	public Set getEmpresaparametroemails() {
		return this.empresaparametroemails;
	}

	public void setEmpresaparametroemails(Set empresaparametroemails) {
		this.empresaparametroemails = empresaparametroemails;
	}

}
