package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * EmailestadoId generated by hbm2java
 */
public class EmailestadoId implements java.io.Serializable {

	private String idemailenvio;
	private String afiliadoid;
	private String nacionalidad;
	private int idtipestadoemail;

	public EmailestadoId() {
	}

	public EmailestadoId(String idemailenvio, String afiliadoid,
			String nacionalidad, int idtipestadoemail) {
		this.idemailenvio = idemailenvio;
		this.afiliadoid = afiliadoid;
		this.nacionalidad = nacionalidad;
		this.idtipestadoemail = idtipestadoemail;
	}

	public String getIdemailenvio() {
		return this.idemailenvio;
	}

	public void setIdemailenvio(String idemailenvio) {
		this.idemailenvio = idemailenvio;
	}

	public String getAfiliadoid() {
		return this.afiliadoid;
	}

	public void setAfiliadoid(String afiliadoid) {
		this.afiliadoid = afiliadoid;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public int getIdtipestadoemail() {
		return this.idtipestadoemail;
	}

	public void setIdtipestadoemail(int idtipestadoemail) {
		this.idtipestadoemail = idtipestadoemail;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmailestadoId))
			return false;
		EmailestadoId castOther = (EmailestadoId) other;

		return ((this.getIdemailenvio() == castOther.getIdemailenvio()) || (this
				.getIdemailenvio() != null
				&& castOther.getIdemailenvio() != null && this
				.getIdemailenvio().equals(castOther.getIdemailenvio())))
				&& ((this.getAfiliadoid() == castOther.getAfiliadoid()) || (this
						.getAfiliadoid() != null
						&& castOther.getAfiliadoid() != null && this
						.getAfiliadoid().equals(castOther.getAfiliadoid())))
				&& ((this.getNacionalidad() == castOther.getNacionalidad()) || (this
						.getNacionalidad() != null
						&& castOther.getNacionalidad() != null && this
						.getNacionalidad().equals(castOther.getNacionalidad())))
				&& (this.getIdtipestadoemail() == castOther
						.getIdtipestadoemail());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdemailenvio() == null ? 0 : this.getIdemailenvio()
						.hashCode());
		result = 37
				* result
				+ (getAfiliadoid() == null ? 0 : this.getAfiliadoid()
						.hashCode());
		result = 37
				* result
				+ (getNacionalidad() == null ? 0 : this.getNacionalidad()
						.hashCode());
		result = 37 * result + this.getIdtipestadoemail();
		return result;
	}

}
