package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * Emailbroadcast generated by hbm2java
 */
public class Emailbroadcast implements java.io.Serializable {

	private EmailbroadcastId id;
	private Afiliado afiliado;
	private Tipoemail tipoemail;
	private Tipoestaestadoemail tipoestaestadoemail;

	public Emailbroadcast() {
	}

	public Emailbroadcast(EmailbroadcastId id, Afiliado afiliado,
			Tipoemail tipoemail, Tipoestaestadoemail tipoestaestadoemail) {
		this.id = id;
		this.afiliado = afiliado;
		this.tipoemail = tipoemail;
		this.tipoestaestadoemail = tipoestaestadoemail;
	}

	public EmailbroadcastId getId() {
		return this.id;
	}

	public void setId(EmailbroadcastId id) {
		this.id = id;
	}

	public Afiliado getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(Afiliado afiliado) {
		this.afiliado = afiliado;
	}

	public Tipoemail getTipoemail() {
		return this.tipoemail;
	}

	public void setTipoemail(Tipoemail tipoemail) {
		this.tipoemail = tipoemail;
	}

	public Tipoestaestadoemail getTipoestaestadoemail() {
		return this.tipoestaestadoemail;
	}

	public void setTipoestaestadoemail(Tipoestaestadoemail tipoestaestadoemail) {
		this.tipoestaestadoemail = tipoestaestadoemail;
	}

}
