package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Empresaparametroemail generated by hbm2java
 */
public class Empresaparametroemail implements java.io.Serializable {

	private EmpresaparametroemailId id;
	private Emailparametro emailparametro;
	private Empresa empresa;
	private BigDecimal valor;

	public Empresaparametroemail() {
	}

	public Empresaparametroemail(EmpresaparametroemailId id,
			Emailparametro emailparametro, Empresa empresa) {
		this.id = id;
		this.emailparametro = emailparametro;
		this.empresa = empresa;
	}

	public Empresaparametroemail(EmpresaparametroemailId id,
			Emailparametro emailparametro, Empresa empresa, BigDecimal valor) {
		this.id = id;
		this.emailparametro = emailparametro;
		this.empresa = empresa;
		this.valor = valor;
	}

	public EmpresaparametroemailId getId() {
		return this.id;
	}

	public void setId(EmpresaparametroemailId id) {
		this.id = id;
	}

	public Emailparametro getEmailparametro() {
		return this.emailparametro;
	}

	public void setEmailparametro(Emailparametro emailparametro) {
		this.emailparametro = emailparametro;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
