package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EmpresaparametroemailId generated by hbm2java
 */
public class EmpresaparametroemailId implements java.io.Serializable {

	private int idempresa;
	private int ideparametro;
	private Date fecha;

	public EmpresaparametroemailId() {
	}

	public EmpresaparametroemailId(int idempresa, int ideparametro, Date fecha) {
		this.idempresa = idempresa;
		this.ideparametro = ideparametro;
		this.fecha = fecha;
	}

	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	public int getIdeparametro() {
		return this.ideparametro;
	}

	public void setIdeparametro(int ideparametro) {
		this.ideparametro = ideparametro;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmpresaparametroemailId))
			return false;
		EmpresaparametroemailId castOther = (EmpresaparametroemailId) other;

		return (this.getIdempresa() == castOther.getIdempresa())
				&& (this.getIdeparametro() == castOther.getIdeparametro())
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdempresa();
		result = 37 * result + this.getIdeparametro();
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
