package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

	private Integer idempresa;
	private String nit;
	private String nombreEmpresa;
	private String direccion;
	private String telefono;
	private String email;
	private String emailNotificaciones;
	private Date creacion;
	private Set empresaparametroemails = new HashSet(0);
	private Set vendedors = new HashSet(0);
	private Set sucursals = new HashSet(0);
	private Set contratos = new HashSet(0);
	private Set afiliados = new HashSet(0);

	public Empresa() {
	}

	public Empresa(String nit, String nombreEmpresa, String direccion,
			String telefono, String emailNotificaciones) {
		this.nit = nit;
		this.nombreEmpresa = nombreEmpresa;
		this.direccion = direccion;
		this.telefono = telefono;
		this.emailNotificaciones = emailNotificaciones;
	}

	public Empresa(String nit, String nombreEmpresa, String direccion,
			String telefono, String email, String emailNotificaciones,
			Set empresaparametroemails, Set vendedors, Set sucursals,
			Set contratos, Set afiliados, Date creacion) {
		this.nit = nit;
		this.nombreEmpresa = nombreEmpresa;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.emailNotificaciones = emailNotificaciones;
		this.empresaparametroemails = empresaparametroemails;
		this.vendedors = vendedors;
		this.sucursals = sucursals;
		this.contratos = contratos;
		this.afiliados = afiliados;
		this.creacion = creacion;
	}

	public Integer getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(Integer idempresa) {
		this.idempresa = idempresa;
	}

	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	public String getNombreEmpresa() {
		return this.nombreEmpresa;
	}

	public void setNombreEmpresa(String nombreEmpresa) {
		this.nombreEmpresa = nombreEmpresa;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmailNotificaciones() {
		return this.emailNotificaciones;
	}

	public void setEmailNotificaciones(String emailNotificaciones) {
		this.emailNotificaciones = emailNotificaciones;
	}

	public Set getEmpresaparametroemails() {
		return this.empresaparametroemails;
	}

	public void setEmpresaparametroemails(Set empresaparametroemails) {
		this.empresaparametroemails = empresaparametroemails;
	}

	public Set getVendedors() {
		return this.vendedors;
	}

	public void setVendedors(Set vendedors) {
		this.vendedors = vendedors;
	}

	public Set getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set sucursals) {
		this.sucursals = sucursals;
	}

	public Set getContratos() {
		return this.contratos;
	}

	public void setContratos(Set contratos) {
		this.contratos = contratos;
	}

	public Set getAfiliados() {
		return this.afiliados;
	}

	public void setAfiliados(Set afiliados) {
		this.afiliados = afiliados;
	}
	
	public Date getCreacion() {
		return creacion;
	}

	
	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

}
