package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Eventowebservice generated by hbm2java
 */
public class Eventowebservice implements java.io.Serializable {

	private Integer ideventowebservice;
	private String descripcion;
	private int prioridad;
	private Set audiwebservices = new HashSet(0);

	public Eventowebservice() {
	}

	public Eventowebservice(String descripcion, int prioridad) {
		this.descripcion = descripcion;
		this.prioridad = prioridad;
	}

	public Eventowebservice(String descripcion, int prioridad,
			Set audiwebservices) {
		this.descripcion = descripcion;
		this.prioridad = prioridad;
		this.audiwebservices = audiwebservices;
	}

	public Integer getIdeventowebservice() {
		return this.ideventowebservice;
	}

	public void setIdeventowebservice(Integer ideventowebservice) {
		this.ideventowebservice = ideventowebservice;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}

	public Set getAudiwebservices() {
		return this.audiwebservices;
	}

	public void setAudiwebservices(Set audiwebservices) {
		this.audiwebservices = audiwebservices;
	}

}
