package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * Globalstats generated by hbm2java
 */
public class Globalstats implements java.io.Serializable {

	private String idmail;
	private String useragent;
	private String ipremota;

	public Globalstats() {
	}

	public Globalstats(String idmail) {
		this.idmail = idmail;
	}

	public Globalstats(String idmail, String useragent, String ipremota) {
		this.idmail = idmail;
		this.useragent = useragent;
		this.ipremota = ipremota;
	}

	public String getIdmail() {
		return this.idmail;
	}

	public void setIdmail(String idmail) {
		this.idmail = idmail;
	}

	public String getUseragent() {
		return this.useragent;
	}

	public void setUseragent(String useragent) {
		this.useragent = useragent;
	}

	public String getIpremota() {
		return this.ipremota;
	}

	public void setIpremota(String ipremota) {
		this.ipremota = ipremota;
	}

}
