package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * Instancia generated by hbm2java
 */
public class Instancia implements java.io.Serializable {

	private InstanciaId id;
	private Contrato contrato;

	public Instancia() {
	}

	public Instancia(InstanciaId id, Contrato contrato) {
		this.id = id;
		this.contrato = contrato;
	}

	public InstanciaId getId() {
		return this.id;
	}

	public void setId(InstanciaId id) {
		this.id = id;
	}

	public Contrato getContrato() {
		return this.contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

}
