package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * InstanciaId generated by hbm2java
 */
public class InstanciaId implements java.io.Serializable {

	private int idinstancia;
	private int idcontrato;
	private int idempresa;

	public InstanciaId() {
	}

	public InstanciaId(int idinstancia, int idcontrato, int idempresa) {
		this.idinstancia = idinstancia;
		this.idcontrato = idcontrato;
		this.idempresa = idempresa;
	}

	public int getIdinstancia() {
		return this.idinstancia;
	}

	public void setIdinstancia(int idinstancia) {
		this.idinstancia = idinstancia;
	}

	public int getIdcontrato() {
		return this.idcontrato;
	}

	public void setIdcontrato(int idcontrato) {
		this.idcontrato = idcontrato;
	}

	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InstanciaId))
			return false;
		InstanciaId castOther = (InstanciaId) other;

		return (this.getIdinstancia() == castOther.getIdinstancia())
				&& (this.getIdcontrato() == castOther.getIdcontrato())
				&& (this.getIdempresa() == castOther.getIdempresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdinstancia();
		result = 37 * result + this.getIdcontrato();
		result = 37 * result + this.getIdempresa();
		return result;
	}

}
