package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {

	private Integer idperfil;
	private String descripcion;
	private String css;
	private Set usuarioperfils = new HashSet(0);

	public Perfil() {
	}

	public Perfil(String descripcion, String css) {
		this.descripcion = descripcion;
		this.css = css;
	}

	public Perfil(String descripcion, String css, Set usuarioperfils) {
		this.descripcion = descripcion;
		this.css = css;
		this.usuarioperfils = usuarioperfils;
	}

	public Integer getIdperfil() {
		return this.idperfil;
	}

	public void setIdperfil(Integer idperfil) {
		this.idperfil = idperfil;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCss() {
		return this.css;
	}

	public void setCss(String css) {
		this.css = css;
	}

	public Set getUsuarioperfils() {
		return this.usuarioperfils;
	}

	public void setUsuarioperfils(Set usuarioperfils) {
		this.usuarioperfils = usuarioperfils;
	}

}
