package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * PermisorolId generated by hbm2java
 */
public class PermisorolId implements java.io.Serializable {

	private int idrol;
	private int idusuario;

	public PermisorolId() {
	}

	public PermisorolId(int idrol, int idusuario) {
		this.idrol = idrol;
		this.idusuario = idusuario;
	}

	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PermisorolId))
			return false;
		PermisorolId castOther = (PermisorolId) other;

		return (this.getIdrol() == castOther.getIdrol())
				&& (this.getIdusuario() == castOther.getIdusuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdrol();
		result = 37 * result + this.getIdusuario();
		return result;
	}

}
