package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer idproducto;
	private String codproducto;
	private String descripcion;
	private Set detransaccions = new HashSet(0);

	public Producto() {
	}

	public Producto(String codproducto) {
		this.codproducto = codproducto;
	}

	public Producto(String codproducto, String descripcion, Set detransaccions) {
		this.codproducto = codproducto;
		this.descripcion = descripcion;
		this.detransaccions = detransaccions;
	}

	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	public String getCodproducto() {
		return this.codproducto;
	}

	public void setCodproducto(String codproducto) {
		this.codproducto = codproducto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getDetransaccions() {
		return this.detransaccions;
	}

	public void setDetransaccions(Set detransaccions) {
		this.detransaccions = detransaccions;
	}

}
