package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Puntos generated by hbm2java
 */
public class Puntos implements java.io.Serializable {

	private PuntosId id;
	private Transaccion transaccion;
	private Afiliado afiliado;
	private int valor;
	private Date fecha;

	public Puntos() {
	}

	public Puntos(PuntosId id, Transaccion transaccion, Afiliado afiliado,
			int valor) {
		this.id = id;
		this.transaccion = transaccion;
		this.afiliado = afiliado;
		this.valor = valor;
	}

	public Puntos(PuntosId id, Transaccion transaccion, Afiliado afiliado,
			int valor, Date fecha) {
		this.id = id;
		this.transaccion = transaccion;
		this.afiliado = afiliado;
		this.valor = valor;
		this.fecha = fecha;
	}

	public PuntosId getId() {
		return this.id;
	}

	public void setId(PuntosId id) {
		this.id = id;
	}

	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	public Afiliado getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(Afiliado afiliado) {
		this.afiliado = afiliado;
	}

	public int getValor() {
		return this.valor;
	}

	public void setValor(int valor) {
		this.valor = valor;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
