package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private Integer idrol;
	private String nombrerol;
	private Set permisorols = new HashSet(0);

	public Rol() {
	}

	public Rol(String nombrerol) {
		this.nombrerol = nombrerol;
	}

	public Rol(String nombrerol, Set permisorols) {
		this.nombrerol = nombrerol;
		this.permisorols = permisorols;
	}

	public Integer getIdrol() {
		return this.idrol;
	}

	public void setIdrol(Integer idrol) {
		this.idrol = idrol;
	}

	public String getNombrerol() {
		return this.nombrerol;
	}

	public void setNombrerol(String nombrerol) {
		this.nombrerol = nombrerol;
	}

	public Set getPermisorols() {
		return this.permisorols;
	}

	public void setPermisorols(Set permisorols) {
		this.permisorols = permisorols;
	}

}
