package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * SmsenvioId generated by hbm2java
 */
public class SmsenvioId implements java.io.Serializable {

	private String idsmsenvio;
	private String afiliadoid;
	private String nacionalidad;

	public SmsenvioId() {
	}

	public SmsenvioId(String idsmsenvio, String afiliadoid, String nacionalidad) {
		this.idsmsenvio = idsmsenvio;
		this.afiliadoid = afiliadoid;
		this.nacionalidad = nacionalidad;
	}

	public String getIdsmsenvio() {
		return this.idsmsenvio;
	}

	public void setIdsmsenvio(String idsmsenvio) {
		this.idsmsenvio = idsmsenvio;
	}

	public String getAfiliadoid() {
		return this.afiliadoid;
	}

	public void setAfiliadoid(String afiliadoid) {
		this.afiliadoid = afiliadoid;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SmsenvioId))
			return false;
		SmsenvioId castOther = (SmsenvioId) other;

		return ((this.getIdsmsenvio() == castOther.getIdsmsenvio()) || (this
				.getIdsmsenvio() != null && castOther.getIdsmsenvio() != null && this
				.getIdsmsenvio().equals(castOther.getIdsmsenvio())))
				&& ((this.getAfiliadoid() == castOther.getAfiliadoid()) || (this
						.getAfiliadoid() != null
						&& castOther.getAfiliadoid() != null && this
						.getAfiliadoid().equals(castOther.getAfiliadoid())))
				&& ((this.getNacionalidad() == castOther.getNacionalidad()) || (this
						.getNacionalidad() != null
						&& castOther.getNacionalidad() != null && this
						.getNacionalidad().equals(castOther.getNacionalidad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdsmsenvio() == null ? 0 : this.getIdsmsenvio()
						.hashCode());
		result = 37
				* result
				+ (getAfiliadoid() == null ? 0 : this.getAfiliadoid()
						.hashCode());
		result = 37
				* result
				+ (getNacionalidad() == null ? 0 : this.getNacionalidad()
						.hashCode());
		return result;
	}

}
