package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Smsenvio generated by hbm2java
 */
public class Smsenvio implements java.io.Serializable {

	private SmsenvioId id;
	private Estadosms estadosms;
	private Afiliado afiliado;
	private Tiposms tiposms;
	private Date fechaenvio;

	public Smsenvio() {
	}

	public Smsenvio(SmsenvioId id, Afiliado afiliado, Tiposms tiposms) {
		this.id = id;
		this.afiliado = afiliado;
		this.tiposms = tiposms;
	}

	public Smsenvio(SmsenvioId id, Estadosms estadosms, Afiliado afiliado,
			Tiposms tiposms, Date fechaenvio) {
		this.id = id;
		this.estadosms = estadosms;
		this.afiliado = afiliado;
		this.tiposms = tiposms;
		this.fechaenvio = fechaenvio;
	}

	public SmsenvioId getId() {
		return this.id;
	}

	public void setId(SmsenvioId id) {
		this.id = id;
	}

	public Estadosms getEstadosms() {
		return this.estadosms;
	}

	public void setEstadosms(Estadosms estadosms) {
		this.estadosms = estadosms;
	}

	public Afiliado getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(Afiliado afiliado) {
		this.afiliado = afiliado;
	}

	public Tiposms getTiposms() {
		return this.tiposms;
	}

	public void setTiposms(Tiposms tiposms) {
		this.tiposms = tiposms;
	}

	public Date getFechaenvio() {
		return this.fechaenvio;
	}

	public void setFechaenvio(Date fechaenvio) {
		this.fechaenvio = fechaenvio;
	}

}
