package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal implements java.io.Serializable {

	private SucursalId id;
	private Usuario usuario;
	private Empresa empresa;
	private String nombreSucursal;
	private String direccion;
	private String email;
	private String codigointerno;
	private String apikey;
	private Set transaccions = new HashSet(0);
	private Set audiwebservices = new HashSet(0);

	public Sucursal() {
	}

	public Sucursal(SucursalId id, Usuario usuario, Empresa empresa,
			String nombreSucursal, String direccion, String codigointerno,
			String apikey) {
		this.id = id;
		this.usuario = usuario;
		this.empresa = empresa;
		this.nombreSucursal = nombreSucursal;
		this.direccion = direccion;
		this.codigointerno = codigointerno;
		this.apikey = apikey;
	}

	public Sucursal(SucursalId id, Usuario usuario, Empresa empresa,
			String nombreSucursal, String direccion, String email,
			String codigointerno, String apikey, Set transaccions,
			Set audiwebservices) {
		this.id = id;
		this.usuario = usuario;
		this.empresa = empresa;
		this.nombreSucursal = nombreSucursal;
		this.direccion = direccion;
		this.email = email;
		this.codigointerno = codigointerno;
		this.apikey = apikey;
		this.transaccions = transaccions;
		this.audiwebservices = audiwebservices;
	}

	public SucursalId getId() {
		return this.id;
	}

	public void setId(SucursalId id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getNombreSucursal() {
		return this.nombreSucursal;
	}

	public void setNombreSucursal(String nombreSucursal) {
		this.nombreSucursal = nombreSucursal;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCodigointerno() {
		return this.codigointerno;
	}

	public void setCodigointerno(String codigointerno) {
		this.codigointerno = codigointerno;
	}

	public String getApikey() {
		return this.apikey;
	}

	public void setApikey(String apikey) {
		this.apikey = apikey;
	}

	public Set getTransaccions() {
		return this.transaccions;
	}

	public void setTransaccions(Set transaccions) {
		this.transaccions = transaccions;
	}

	public Set getAudiwebservices() {
		return this.audiwebservices;
	}

	public void setAudiwebservices(Set audiwebservices) {
		this.audiwebservices = audiwebservices;
	}

}
