package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * SucursalId generated by hbm2java
 */
public class SucursalId implements java.io.Serializable {

	private int idsucursal;
	private int idempresa;

	public SucursalId() {
	}

	public SucursalId(int idsucursal, int idempresa) {
		this.idsucursal = idsucursal;
		this.idempresa = idempresa;
	}

	public int getIdsucursal() {
		return this.idsucursal;
	}

	public void setIdsucursal(int idsucursal) {
		this.idsucursal = idsucursal;
	}

	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SucursalId))
			return false;
		SucursalId castOther = (SucursalId) other;

		return (this.getIdsucursal() == castOther.getIdsucursal())
				&& (this.getIdempresa() == castOther.getIdempresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdsucursal();
		result = 37 * result + this.getIdempresa();
		return result;
	}

}
