package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tipodocumento generated by hbm2java
 */
public class Tipodocumento implements java.io.Serializable {

	private Integer idtipodocumento;
	private String descripcion;
	private Set afiliados = new HashSet(0);

	public Tipodocumento() {
	}

	public Tipodocumento(String descripcion) {
		this.descripcion = descripcion;
	}

	public Tipodocumento(String descripcion, Set afiliados) {
		this.descripcion = descripcion;
		this.afiliados = afiliados;
	}

	public Integer getIdtipodocumento() {
		return this.idtipodocumento;
	}

	public void setIdtipodocumento(Integer idtipodocumento) {
		this.idtipodocumento = idtipodocumento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getAfiliados() {
		return this.afiliados;
	}

	public void setAfiliados(Set afiliados) {
		this.afiliados = afiliados;
	}

}
