package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tipoestaestadoemail generated by hbm2java
 */
public class Tipoestaestadoemail implements java.io.Serializable {

	private Integer idtipoestaestadoemail;
	private String descripcion;
	private String codigostandarid;
	private Set emailbroadcasts = new HashSet(0);
	private Set emailestados = new HashSet(0);

	public Tipoestaestadoemail() {
	}

	public Tipoestaestadoemail(String descripcion) {
		this.descripcion = descripcion;
	}

	public Tipoestaestadoemail(String descripcion, String codigostandarid,
			Set emailbroadcasts, Set emailestados) {
		this.descripcion = descripcion;
		this.codigostandarid = codigostandarid;
		this.emailbroadcasts = emailbroadcasts;
		this.emailestados = emailestados;
	}

	public Integer getIdtipoestaestadoemail() {
		return this.idtipoestaestadoemail;
	}

	public void setIdtipoestaestadoemail(Integer idtipoestaestadoemail) {
		this.idtipoestaestadoemail = idtipoestaestadoemail;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodigostandarid() {
		return this.codigostandarid;
	}

	public void setCodigostandarid(String codigostandarid) {
		this.codigostandarid = codigostandarid;
	}

	public Set getEmailbroadcasts() {
		return this.emailbroadcasts;
	}

	public void setEmailbroadcasts(Set emailbroadcasts) {
		this.emailbroadcasts = emailbroadcasts;
	}

	public Set getEmailestados() {
		return this.emailestados;
	}

	public void setEmailestados(Set emailestados) {
		this.emailestados = emailestados;
	}

}
