package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario implements java.io.Serializable {

	private Integer idtipousuario;
	private String descripcion;
	private Set usuarios = new HashSet(0);

	public Tipousuario() {
	}

	public Tipousuario(String descripcion) {
		this.descripcion = descripcion;
	}

	public Tipousuario(String descripcion, Set usuarios) {
		this.descripcion = descripcion;
		this.usuarios = usuarios;
	}

	public Integer getIdtipousuario() {
		return this.idtipousuario;
	}

	public void setIdtipousuario(Integer idtipousuario) {
		this.idtipousuario = idtipousuario;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
