package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioperfilId generated by hbm2java
 */
public class UsuarioperfilId implements java.io.Serializable {

	private int idusuario;
	private int idperfil;

	public UsuarioperfilId() {
	}

	public UsuarioperfilId(int idusuario, int idperfil) {
		this.idusuario = idusuario;
		this.idperfil = idperfil;
	}

	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	public int getIdperfil() {
		return this.idperfil;
	}

	public void setIdperfil(int idperfil) {
		this.idperfil = idperfil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioperfilId))
			return false;
		UsuarioperfilId castOther = (UsuarioperfilId) other;

		return (this.getIdusuario() == castOther.getIdusuario())
				&& (this.getIdperfil() == castOther.getIdperfil());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdusuario();
		result = 37 * result + this.getIdperfil();
		return result;
	}

}
