package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private Tipousuario tipousuario;
	private String descripcion;
	private Set afiliados = new HashSet(0);
	private Set sucursals = new HashSet(0);
	private Usuarioweb usuarioweb;

	public Usuario() {
	}

	public Usuario(String descripcion) {
		this.descripcion = descripcion;
	}

	public Usuario(Tipousuario tipousuario, String descripcion, Set afiliados,
			Set sucursals, Usuarioweb usuarioweb) {
		this.tipousuario = tipousuario;
		this.descripcion = descripcion;
		this.afiliados = afiliados;
		this.sucursals = sucursals;
		this.usuarioweb = usuarioweb;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public Tipousuario getTipousuario() {
		return this.tipousuario;
	}

	public void setTipousuario(Tipousuario tipousuario) {
		this.tipousuario = tipousuario;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getAfiliados() {
		return this.afiliados;
	}

	public void setAfiliados(Set afiliados) {
		this.afiliados = afiliados;
	}

	public Set getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set sucursals) {
		this.sucursals = sucursals;
	}

	public Usuarioweb getUsuarioweb() {
		return this.usuarioweb;
	}

	public void setUsuarioweb(Usuarioweb usuarioweb) {
		this.usuarioweb = usuarioweb;
	}

}
