package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * Usuarioperfil generated by hbm2java
 */
public class Usuarioperfil implements java.io.Serializable {

	private UsuarioperfilId id;
	private Perfil perfil;
	private Usuarioweb usuarioweb;
	private String descripcion;

	public Usuarioperfil() {
	}

	public Usuarioperfil(UsuarioperfilId id, Perfil perfil,
			Usuarioweb usuarioweb, String descripcion) {
		this.id = id;
		this.perfil = perfil;
		this.usuarioweb = usuarioweb;
		this.descripcion = descripcion;
	}

	public UsuarioperfilId getId() {
		return this.id;
	}

	public void setId(UsuarioperfilId id) {
		this.id = id;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public Usuarioweb getUsuarioweb() {
		return this.usuarioweb;
	}

	public void setUsuarioweb(Usuarioweb usuarioweb) {
		this.usuarioweb = usuarioweb;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
