package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor implements java.io.Serializable {

	private VendedorId id;
	private Empresa empresa;
	private String nombres;
	private String apellidos;
	private boolean actvo;

	public Vendedor() {
	}

	public Vendedor(VendedorId id, Empresa empresa, String nombres,
			String apellidos, boolean actvo) {
		this.id = id;
		this.empresa = empresa;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.actvo = actvo;
	}

	public VendedorId getId() {
		return this.id;
	}

	public void setId(VendedorId id) {
		this.id = id;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public boolean isActvo() {
		return this.actvo;
	}

	public void setActvo(boolean actvo) {
		this.actvo = actvo;
	}

}
