package com.dromedicas.dto;

// Generated 31/10/2016 11:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * VendedorId generated by hbm2java
 */
public class VendedorId implements java.io.Serializable {

	private String docuvendedor;
	private int idempresa;

	public VendedorId() {
	}

	public VendedorId(String docuvendedor, int idempresa) {
		this.docuvendedor = docuvendedor;
		this.idempresa = idempresa;
	}

	public String getDocuvendedor() {
		return this.docuvendedor;
	}

	public void setDocuvendedor(String docuvendedor) {
		this.docuvendedor = docuvendedor;
	}

	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VendedorId))
			return false;
		VendedorId castOther = (VendedorId) other;

		return ((this.getDocuvendedor() == castOther.getDocuvendedor()) || (this
				.getDocuvendedor() != null
				&& castOther.getDocuvendedor() != null && this
				.getDocuvendedor().equals(castOther.getDocuvendedor())))
				&& (this.getIdempresa() == castOther.getIdempresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDocuvendedor() == null ? 0 : this.getDocuvendedor()
						.hashCode());
		result = 37 * result + this.getIdempresa();
		return result;
	}

}
